concurrent = 1
check_interval = 0
connection_max_age = "15m0s"
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "terraform"
  url = "http://gitlab.local/"
  id = 2
  token = "glrtr-EEBmxDuxyRBVxGSeJCZv"
  token_obtained_at = 2025-05-16T11:15:10Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "hashicorp/terraform:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache", "/etc/gitlab-runner/certs/gitlab.local.crt:/etc/ssl/certs/gitlab.local.crt:ro"] # This line is critical
    shm_size = 0
    network_mtu = 0
